name: Cypress Test
on:
  push:
    branches:
      - main
  schedule:
      - cron: "15 9 * * 1-5"  # 15 minutes, 9 hours, any day of the month, every month, monday to friday
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Cypress.io 
        uses: cypress-io/github-action@v6.5.0
        with:
          browser: chrome
